apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: vasizebron/notification_video2mp3
          envFrom:
            - configMapRef:
                name: notification-configmap
            - secretRef:
                name: notification-secret

